### ISSUE TITLE
Error for FlashAttention

### ISSUE THREAD

**Issue by shuxjweb** [baaivision/tokenize-anything#10]
The code will report error when running with V100 GPU:
RuntimeError: FlashAttention only supports Ampere GPUs or newer.

Since I have only V100 GPU, how can I change the code? For example, o = self.cache.forward_flash(self, q, k, v)

class Attention(nn.Module):
    """Self-Attention layer."""

    def __init__(self, dim, num_heads, bias=True):
        super(Attention, self).__init__()
        self.qkv = nn.Linear(dim, dim * 3, bias=bias)
        self.proj = nn.Linear(dim, dim, bias=bias)
        self.head_dim = dim // num_heads
        self.num_heads = num_heads
        self.scale = self.head_dim**-0.5
        self.dropout = nn.Dropout(0.1, inplace=False)
        self.cache = nn.Module()

    def forward(self, x):
        qkv_shape = (-1, x.size(1), 3, self.num_heads, self.head_dim)
        q, k, v = self.qkv(x).view(qkv_shape).unbind(dim=2)
        q, k = self.cache.forward_rotary(q, k, inplace=True)
        o = self.cache.forward_flash(self, q, k, v)
        return self.proj(o.flatten(2))

class Attention(nn.Module):
    """Multi-head attention."""

    def __init__(self, dim=256, num_heads=8, attn_ratio=1):
        super(Attention, self).__init__()
        qkv_dim = int(dim * attn_ratio)
        self.num_heads = num_heads
        self.head_dim = qkv_dim // num_heads
        self.q_proj = nn.Linear(dim, qkv_dim)
        self.k_proj = nn.Linear(dim, qkv_dim)
        self.v_proj = nn.Linear(dim, qkv_dim)
        self.proj = nn.Linear(qkv_dim, dim)
        self.scale = self.head_dim**-0.5

    def forward(self, q, k, v):
        q = self.q_proj(q).view((-1, q.size(1), self.num_heads, self.head_dim))  
        k = self.k_proj(k).view((-1, k.size(1), self.num_heads, self.head_dim))    
        v = self.v_proj(v).view((-1, v.size(1), self.num_heads, self.head_dim))  
        o = flash_attn_func(q, k, v, softmax_scale=self.scale)             
        o = F.scaled_dot_product_attention(q, k, v, is_causal=True)[0] 
        return self.proj(o.flatten(2))

**Comment by PhyscalX** [comment]
Hi, @shuxjweb 
1. Fallback for the attention in ImageDecoder is just ``scaled_dot_product_attention``
2. Fallback for the attention in TextDecoder (i.e., a mini Llama) is more complex, you should reimplement ``causal masking``, ``rotary embedding`` and ``kvcache updater``, you can refer the official Llama code for the technical details.

**Comment by shuxjweb** [comment]
Thanks for you reply.
