### ISSUE TITLE
The gt label for captions how to gernerated ?

### ISSUE THREAD

**Issue by fujianhai** [baaivision/tokenize-anything#8]
I have a question, The gt label for captions how to gernerated ?

**Comment by PhyscalX** [comment]
Hi, @fujianhai 

We freeze the image encoder-decoder during caption training. Classification labels are unnecessary.

For ground-truth caption, we use [GRIT](https://github.com/JialianW/GRiT) preprocessed train [JSON](https://datarelease.blob.core.windows.net/grit/VG_preprocessed_annotations/train.json), and test [JSON](https://datarelease.blob.core.windows.net/grit/VG_preprocessed_annotations/test.json). 
These JSON files contain only boxes and captions.

**Comment by fujianhai** [comment]
@PhyscalX , thank you very much， are you train the caption info on like coco caption data?

**Comment by PhyscalX** [comment]
No. 
VisualGenome is currently the largest public *RegionCaption* dataset.
COCO caption and other Image-Text datasets are typical *ImageCaption* datasets.
